config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'help' => "pages#help"
  get 'measures' => "pages#measures"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def measures
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- How do I link an image to root_path? How do I get img path relative to root_path? --><img src="assets/wordmark-white.png" id="logo" alt="Able">
    </div>
  

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
     
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log in", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_measures.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h2 class="account-label">Shreveport Internal Medicine</h2>
		<h2 class="report-label">PQRS 2015</h2>
	</div>
</div>
<div class="panel panel-primary">
	<div class="panel-body">
		<div class="row">
		 	<div class="col-xs-6 col-md-6"><h4>Diabetes: Hemoglobin A1c Poor Control</h4><p>PQRS #1 (NQF 0059)</p><p>Effective Clinical Care</p>
		 	</div>
	 		<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			20/60
	 		</div>
	 		<div class="col-xs-4 col-md-4">
	 			<br />
	 			<br />
	 			<div class="progress">
					<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">30%
					</div>
				</div>
			</div>
			<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			More
	 		</div>
		</div>
	</div>
</div>

<div class="panel panel-primary">
	<div class="panel-body">
		<div class="row">
		 	<div class="col-xs-6 col-md-6"><h4>Heart Failure (HF): Angiotensin-Converting Enzyme (ACE) Inhibitor or Angiotensin Receptor Blocker (ARB) Therapy for Left Ventricular Systolic Dysfunction (LVSD)</h4><p>#5 (NQF 0081)</p><p>Effective Clinical Care</p>
		 	</div>
	 		<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			<br />
	 			90/120
	 		</div>
	 		<div class="col-xs-4 col-md-4">
	 			<br />
	 			<br />
	 			<br />
	 			<div class="progress">
					<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">80%
					</div>
				</div>
			</div>
	 		<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			<br />
	 			More
	 		</div>
		</div>
	</div>
</div>

<div class="panel panel-primary">
	<div class="panel-body">
		<div class="row">
		 	<div class="col-xs-6 col-md-6"><h4>HStroke and Stroke Rehabilitation: Anticoagulant Therapy Prescribed for Atrial Fibrillation (AF) at Discharge</h4><p>PQRS #33 (NQF 0241)</p><p>Effective Clinical Care</p>
		 	</div>
	 		<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			60/100
	 		</div>
	 		<div class="col-xs-4 col-md-4">
	 			<br />
	 			<br />
	 			<div class="progress">
					<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">60%
					</div>
				</div>
			</div>
			<div class="col-xs-1 col-md-1">
	 			<br />
	 			<br />
	 			More
	 		</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Able Health</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render "layouts/header"%>
	<div class="container">
		<% flash.each do |name, msg| %>
	    	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/help.html.erb
<div class="jumbotron">
	<h2> Help </h2>
	<p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.  </p>
</div>

app/views/pages/home.html.erb
<div class="container container-body">
	<% if user_signed_in? %>
		<%= render "layouts/measures"%>
	<% else %>	
		<div class="intro-text">
			<h1>Welcome to Able</h1>
		</div>
		<div class="jumbotron center">	
			<%= form_for(:user, :url => session_path(:user)) do |f| %>
				<div class="form-group">
			        <!--<%= f.label :email %>-->
			        <%= f.email_field :email, autofocus: true, class: "form-control" %>
			    </div>

				<div class="form-group">
			        <!--<%= f.label :password %>-->
			        <%= f.password_field :password, class: "form-control" %>
			    </div>

				<!-- <%= f.check_box :remember_me %>
				<%= f.label :remember_me %> -->

				<div class="form-group">
					<%= f.submit 'Log in', class: "btn btn-primary btn-lg" %>
				</div>

				<p><%= link_to "Forgot your password?", new_password_path(:user) %> </p>
				
				<!--<%= link_to "Sign up", new_registration_path(:user) %>-->
			<% end %>
		</div>
		<div class="disclaimer">
			<p><%= link_to "Able is HIPAA compliant", help_path %></p>
		</div>
	<% end %>
</div>